general.import = ["~/.cache/wal/colors-alacritty.toml"]
general.live_config_reload = true

[window]
opacity = 0.95
decorations = "Full"

[font]
normal.family = "Caskaydia Cove Nerd Font Mono"
size = 12.0

[terminal]
shell.program = "/usr/bin/zsh"
